import webbrowser
from functools import partial
from PySide6 import QtGui, QtWidgets
from PySide6.QtCore import Qt
from embarker.resources import get_icon
from embarker.appinfos import DW_GITHUB, DW_WEBSITE, ABOUT, DOC_WEBSITE
import embarker.commands as ebc


def get_default_actions(mainwindow):
    return [
        {
            'id': 'About',
            'text': 'About',
            'category': 'Help',
            'icon': None,
            'group': None,
            'method': lambda: QtWidgets.QMessageBox.about(
                mainwindow, 'About', ABOUT),
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'AboutDreamwall',
            'text': 'About &DreamWall',
            'category': 'Help',
            'icon': None,
            'group': None,
            'method': partial(webbrowser.open, DW_WEBSITE),
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'AboutTools',
            'text': 'Explore DreamWall Tools',
            'category': 'Help',
            'icon': None,
            'group': None,
            'method': partial(webbrowser.open, DW_GITHUB),
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'AddVideos',
            'text': 'Add Videos',
            'category': 'Playlist',
            'icon': None,
            'group': None,
            'method': ebc.prompt_load_videos,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'Copy',
            'text': 'Copy',
            'category': 'Global',
            'icon': None,
            'group': None,
            'method': mainwindow.copy,
            'checkable': False,
            'shortcut': 'CTRL+C',
        },
        {
            'id': 'DefaultState',
            'text': 'Restore default workspace',
            'category': 'View',
            'icon': None,
            'group': None,
            'method': mainwindow.restore_default_state,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'DeleteCurrentAnnotation',
            'text': 'Delete current annotation',
            'category': 'Session',
            'icon': None,
            'group': None,
            'method': ebc.delete_annotation,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'DisplayPluginManagerWindow',
            'text': 'Plugins',
            'category': 'Global',
            'icon': None,
            'group': None,
            'method': mainwindow.plugin_manager.show,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'DisplayShortcutManager',
            'text': 'Shortcuts',
            'category': 'Global',
            'icon': None,
            'group': None,
            'method': mainwindow.shortcut_manager.show,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'DisplayEnvironment',
            'text': 'Environment',
            'category': 'Global',
            'icon': None,
            'group': None,
            'method': mainwindow.show_environment,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'Documentation',
            'text': 'Documentation',
            'category': 'Help',
            'icon': None,
            'group': None,
            'method': partial(webbrowser.open, DOC_WEBSITE),
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'Exit',
            'text': 'E&xit',
            'category': 'Global',
            'icon': None,
            'group': None,
            'method': partial(QtWidgets.QApplication.exit, 0),
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.CTRL | Qt.Key_Q),
        },
        {
            'id': 'ExportImage',
            'text': 'Export current annotation',
            'category': 'Session',
            'icon': get_icon('export_image.png'),
            'group': None,
            'method': ebc.export_current_frame,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'ExportImages',
            'text': 'Export annotations',
            'category': 'Session',
            'icon': get_icon('export_images.png'),
            'group': None,
            'method': ebc.export_annotated_frames,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'ExportPreferences',
            'text': 'Export preferences',
            'category': 'Global',
            'icon': None,
            'group': None,
            'method': ebc.export_preferences,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'FullScreen',
            'text': 'Toggle full screen',
            'category': 'View',
            'icon': None,
            'group': None,
            'method': mainwindow.toggle_fullscreen,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.Key.Key_F11),
        },
        {
            'id': 'InsertVideos',
            'text': 'Insert videos',
            'category': 'Playlist',
            'icon': None,
            'group': None,
            'method': partial(ebc.prompt_load_videos, True),
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'InsertVideosAfter',
            'text': 'Insert videos after current video',
            'category': 'Playlist',
            'icon': None,
            'group': None,
            'method': partial(
                ebc.prompt_load_videos, True, True),
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'ImportPlaylist',
            'text': 'Import Playlist',
            'category': 'Playlist',
            'icon': None,
            'group': None,
            'method': ebc.load_playlist,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'ImportPreferences',
            'text': 'Import preferences',
            'category': 'Global',
            'icon': None,
            'group': None,
            'method': ebc.import_preferences,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'ImportSessionAnnotations',
            'text': 'Import session annotations',
            'category': 'Global',
            'icon': None,
            'group': None,
            'method': ebc.import_session_annotations_prompt,
            'checkable': False,
            'shortcut':  QtGui.QKeySequence(Qt.CTRL | Qt.SHIFT | Qt.Key_I),
        },
        {
            'id': 'OpenVideos',
            'text': 'Open videos',
            'category': 'Playlist',
            'icon': get_icon('open_videos.png'),
            'group': None,
            'method': mainwindow.prompt_for_video,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'OpenSession',
            'text': 'Open session',
            'category': 'Global',
            'icon': get_icon('open_session.png'),
            'group': None,
            'method': ebc.open_session,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.CTRL | Qt.Key_O),
        },
        {
            'id': 'NewSession',
            'text': 'New Session',
            'category': 'Global',
            'icon': get_icon('new.png'),
            'group': None,
            'method': ebc.new_session,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.CTRL | Qt.Key_N),
        },
        {
            'id': 'NextAnnotation',
            'text': 'Next annotation',
            'category': 'Navigation',
            'icon': get_icon('next_annotation.png'),
            'group': None,
            'method': ebc.set_next_annotation,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.CTRL | Qt.Key_Right),
        },
        {
            'id': 'NextFrame',
            'text': 'Next frame',
            'category': 'Navigation',
            'icon': get_icon('next_frame.svg'),
            'group': None,
            'method': ebc.next_frame,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.Key_Right),
        },
        {
            'id': 'NextVideo',
            'text': 'Next Video',
            'category': 'Navigation',
            'icon': get_icon('next_track.png'),
            'group': None,
            'method': ebc.set_next_video,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.SHIFT | Qt.Key_Right),
        },
        {
            'id': 'Paste',
            'text': 'Paste',
            'category': 'Global',
            'icon': None,
            'group': None,
            'method': mainwindow.paste,
            'checkable': False,
            'shortcut': 'CTRL+V',
        },
        {
            'id': 'PrevAnnotation',
            'text': 'Previous annotation',
            'category': 'Navigation',
            'icon': get_icon('previous_annotation.png'),
            'group': None,
            'method': ebc.set_previous_annotation,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.CTRL | Qt.Key_Left),
        },
        {
            'id': 'PrevFrame',
            'text': 'Previous frame',
            'category': 'Navigation',
            'icon': get_icon('previous_frame.svg'),
            'group': None,
            'method': ebc.previous_frame,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.Key_Left),
        },
        {
            'id': 'PrevVideo',
            'text': 'Previous video',
            'category': 'Navigation',
            'icon': get_icon('previous_track.png'),
            'group': None,
            'method': ebc.set_previous_video,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.SHIFT | Qt.Key_Left),
        },
        {
            'id': 'PlayPause',
            'text': 'Play/Pause',
            'category': 'Navigation',
            'icon': get_icon('play_pause.svg'),
            'group': None,
            'method': ebc.play_pause,
            'checkable': True,
            'shortcut': QtGui.QKeySequence(Qt.Key_Space),
        },
        {
            'id': 'ResetCanvas',
            'text': 'Reset canvas zoom',
            'category': 'Navigation',
            'icon': None,
            'group': None,
            'method': ebc.reset_canvas,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.Key_F),
        },
        {
            'id': 'RemoveCurrentVideo',
            'text': 'Remove current video',
            'category': 'Playlist',
            'icon': None,
            'group': None,
            'method': ebc.remove_current_video,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'RelocateFileVideos',
            'text': 'Relocate file videos',
            'category': 'Global',
            'icon': None,
            'group': None,
            'method': mainwindow.show_relocator,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'SaveSession',
            'text': 'Save session',
            'category': 'Global',
            'icon': get_icon('save.png'),
            'group': None,
            'method': ebc.save,
            'checkable': False,
            'shortcut':  QtGui.QKeySequence(Qt.CTRL | Qt.Key_S),
        },
        {
            'id': 'SaveSessionAs',
            'text': 'Save session as',
            'category': 'Global',
            'icon': get_icon('save.png'),
            'group': None,
            'method': ebc.save_as,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'ExportVideoSessionAs',
            'text': 'Export current video session',
            'category': 'Global',
            'icon': get_icon('save.png'),
            'group': None,
            'method': ebc.export_current_video_session,
            'checkable': False,
            'shortcut': None,
        },
        {
            'id': 'SetPlaybackStart',
            'text': 'Set playback start',
            'category': 'Navigation',
            'icon': None,
            'group': None,
            'method': ebc.set_playback_start,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.Key.Key_I),
        },
        {
            'id': 'SetPlaybackEnd',
            'text': 'Set playback end',
            'category': 'Navigation',
            'icon': None,
            'group': None,
            'method': ebc.set_playback_end,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.Key.Key_O),
        },
        {
            'id': 'Stop',
            'text': 'Stop',
            'category': 'Navigation',
            'icon': get_icon('stop.png'),
            'group': None,
            'method': mainwindow.media_player.stop,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.Key.Key_O),
        },
        {
            'id': 'ToggleOnionSkin',
            'text': 'Onion skin',
            'category': 'View',
            'icon': None,
            'group': None,
            'method': ebc.toggle_onionskin,
            'checkable': True,
            'shortcut': QtGui.QKeySequence(Qt.CTRL | Qt.Key_W),
        },
        {
            'id': 'ToggleLoopMode',
            'text': 'Loop On/Off',
            'category': 'Navigation',
            'icon': get_icon('loop.png'),
            'group': None,
            'method': ebc.toggle_loop_mode,
            'checkable': True,
            'shortcut': QtGui.QKeySequence(Qt.CTRL | Qt.Key.Key_L),
        },
        {
            'id': 'ToggleMute',
            'text': 'Mute On/Off',
            'category': 'Playlist',
            'icon': get_icon('mute.png'),
            'group': None,
            'method': ebc.toggle_mute_sound,
            'checkable': True,
            'shortcut': QtGui.QKeySequence(Qt.Key.Key_M),
        },
        {
            'id': 'ToggleMuteAnnotations',
            'text': 'Mute annotations On/Off',
            'category': 'Playlist',
            'icon': None,
            'group': None,
            'method': ebc.toggle_mute_annotations,
            'checkable': True,
            'shortcut': QtGui.QKeySequence(Qt.Key.Key_W),
        },
        {
            'id': 'ZenMode',
            'text': 'Zen mode On/Off',
            'category': 'View',
            'icon': None,
            'group': None,
            'method': mainwindow.switch_zenmode,
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.Key.Key_Tab),
        },
        {
            'id': 'Zoom1',
            'text': 'Zoom to 100%',
            'category': 'View',
            'group': None,
            'icon': None,
            'method': partial(mainwindow.set_pixel_size, 1),
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.Key.Key_1),
        },
        {
            'id': 'Zoom2',
            'text': 'Zoom to 150%',
            'category': 'View',
            'group': None,
            'icon': None,
            'method': partial(mainwindow.set_pixel_size, 1.5),
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.Key.Key_2),
        },
        {
            'id': 'Zoom3',
            'text': 'Zoom to 200%',
            'category': 'View',
            'group': None,
            'icon': None,
            'method': partial(mainwindow.set_pixel_size, 2),
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.Key.Key_3),
        },
        {
            'id': 'Zoom4',
            'text': 'Zoom to 300%',
            'category': 'View',
            'icon': None,
            'group': None,
            'method': partial(mainwindow.set_pixel_size, 3),
            'checkable': False,
            'shortcut': QtGui.QKeySequence(Qt.Key.Key_3),
        }
    ]
